import { Geist, Geist_Mono } from "next/font/google";
import '@splidejs/splide/dist/css/splide.min.css';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Farras - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* === Tambahkan ini di bawah semua konten === */}
        <a
          href="#home"
          className="fixed bottom-4 left-4 flex items-center justify-center w-10 h-10 bg-white rounded-full shadow-lg hover:scale-105 transition-transform"
        >
          <img
            src="/skils/logo-farras.png"
            alt="Logo Farras"
            className="w-6 h-6 object-contain"
          />
        </a>
      </body>
    </html>
  );
}

